---
# use ./deploy.sh (not this playbook!) to deploy
- hosts: webservers
  gather_facts: no

  tasks:
    - name: upload an artifact
      copy: src=./infrastructure/qs.jar
        dest=/var/projects/quicksilver-latest.jar
        force=yes

    # - name: upload static
    #   copy: src=../resources/public
    #     dest=/var/projects/quicksilver/

    - name: copy an artifact
      shell: cp /var/projects/quicksilver-latest.jar /var/projects/quicksilver-`date -u -Iseconds`.jar

    - name: restart app
      service: name=quicksilver.service state=restarted
      sudo: true
      sudo_user: root
