---
- hosts: webservers
  remote_user: root
  gather_facts: no
  vars_files:
    - vars/database.yaml

  tasks:
    - file: src=/usr/share/zoneinfo/UTC dest=/etc/localtime state=link force=yes
    - file: path=/var/projects/ state=directory mode=0755
    - file: path=/var/log/quicksilver/ state=directory mode=0755
    - copy: src=./quicksilver-upstart.service dest=/lib/systemd/system/quicksilver.service
    - file: path=/etc/sysconfig/quicksilver state=touch mode=0755
    - name: check ENV DB_PASSWORD
      lineinfile: dest=/etc/sysconfig/quicksilver
                  regexp='^DB_PASSWORD='
                  line='DB_PASSWORD="{{db_password}}"'
                  state=present

    - name: check ENV SESSION_SECRET
      lineinfile: dest=/etc/sysconfig/quicksilver
                  regexp='^SESSION_SECRET='
                  line='SESSION_SECRET="{{session_secret}}"'
                  state=present

    - name: check ENV POSTMARK_TOKEN
      lineinfile: dest=/etc/sysconfig/quicksilver
                  regexp='^POSTMARK_TOKEN='
                  line='POSTMARK_TOKEN="{{postmark_token}}"'
                  state=present

    - name: check ENV NOMAD_ENV
      lineinfile: dest=/etc/sysconfig/quicksilver
                  regexp='^NOMAD_ENV='
                  line="NOMAD_ENV=prod"
                  state=present

    - name: update yum
      shell: rpm -iUvh http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm && yum -y update

    - name: install java
      yum: name=java-1.6.0-openjdk-devel

    - name: install lein
      shell: wget https://github.com/technomancy/leiningen/raw/stable/bin/lein --no-check-certificate -O /usr/local/bin/lein

    - name: make lein executable
      shell: chmod 775 /usr/local/bin/lein

    - name: install nginx
      yum: name=nginx

    - name: copy certs
      copy: src=~/bwd_cat/{{item}} dest=/etc/ssl/{{item}}
      with_items:
        - bwd.cat.chained.crt
        - bwd.cat.key
      notify: reload nginx

    - name: configure nginx
      copy: src=./quicksilver-nginx.conf dest=/etc/nginx/conf.d/default.conf
      notify: reload nginx

    - service: name=nginx
                enabled=yes
                state=started

  handlers:
    - name: reload nginx
      service: name=nginx
                state=reloaded
